### ISSUE TITLE
Not Able to register

### ISSUE THREAD

**Issue by DesaiSiddhesh1** [i-vishi/shopping-android-app#9]
I am not able to login to the app while register to app it is saying some error occured.

**Comment by DesaiSiddhesh1** [comment]
![image](https://user-images.githubusercontent.com/101202428/170764613-83be1cbd-9b2b-427d-b148-2910ad2210d8.png)
Showing this line

**Comment by kushal74** [comment]
Bro did you find solution for this issue i cannot logt
